#! /bin/bash

# for parallel builds
export CPUCOUNT=`cat /proc/cpuinfo | grep vendor_id | wc -l`
export PERL_AUTOINSTALL="--defaultdeps"
export TEST_JOBS=${CPUCOUNT}
export CPAN=/opt/tapper/perl/perls/current/bin/cpan
$CPAN Tapper::Installer
$CPAN Tapper::PRC
