#! /bin/bash

# for parallel builds
export CPUCOUNT=`cat /proc/cpuinfo | grep vendor_id | wc -l`
export TWMC_TEST_PORT=9876
export PERL_AUTOINSTALL="--defaultdeps"
export TEST_JOBS=${CPUCOUNT}
export CPAN=/opt/tapper/perl/perls/current/bin/cpan
$CPAN Tapper::Installer
$CPAN Tapper::PRC
$CPAN Tapper::TestSuite::AutoTest
$CPAN Tapper::TestSuite::HWTrack
