#! /bin/bash

# for parallel builds
export CPUCOUNT=`cat /proc/cpuinfo | grep vendor_id | wc -l`

# setup locales
apt-get --yes --allow-unauthenticated install locales
echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
/usr/sbin/locale-gen

# prepare example files
cd /tmp
tar xzf tapper-starterkit.tgz

# some utils
apt-get --yes --allow-unauthenticated install curl
apt-get --yes --allow-unauthenticated install make
apt-get --yes --allow-unauthenticated install gcc
apt-get --yes --allow-unauthenticated install less
apt-get --yes --allow-unauthenticated install perl-modules
apt-get --yes --allow-unauthenticated install openssh-server
apt-get --yes --allow-unauthenticated install nfs-common
# Bug with nfs-common
/var/lib/dpkg/info/nfs-common.postinst

# set default password
echo "root:tapper" | chpasswd

# Install Perl
cd /tmp
export PERLVERSION=5.12.3
export PERLBREW_ROOT=/opt/tapper/perl
mkdir -p $PERLBREW_ROOT
curl -LO http://xrl.us/perlbrew
chmod +x perlbrew
./perlbrew install
/opt/tapper/perl/bin/perlbrew init
echo ". /opt/tapper/perl/etc/bashrc" >> $HOME/.bashrc
. /opt/tapper/perl/etc/bashrc
perlbrew install -j ${CPUCOUNT} perl-${PERLVERSION}
perlbrew switch perl-${PERLVERSION}

# CPAN config
cp /tmp/tapper-starterkit/misc/CPAN-Config.pm /opt/tapper/perl/perls/perl-${PERLVERSION}/lib/${PERLVERSION}/CPAN/Config.pm
export PERL_AUTOINSTALL="--defaultdeps"
export TEST_JOBS=${CPUCOUNT}
export CPAN=/opt/tapper/perl/perls/current/bin/cpan
echo "reload index" | $CPAN

# Install Tapper::Installer
$CPAN Tapper::Installer
cp /opt/tapper/perl/perls/current/bin/tapper-installer-client.pl /etc/init.d/tapper
chmod +x /etc/init.d/tapper
insserv tapper

# create the required files and directories

mkdir -p /mnt/target/
mkdir -p /mnt/guests
mkdir -p /data/tapper

# copy basic Log4Perl config
cp /tmp/tapper-starterkit/etc/log4perl.cfg /etc/log4perl.cfg

# Create devices needed for login
mknod /dev/ttyS0 c 4 64
mknod /dev/ttyS1 c 4 65

# Disable local logins to avoid these warnings:
# 'INIT: Id "4" respawning too fast: disabled for 5 minutes'
cd /etc/
patch -p1 -N < /tmp/tapper-starterkit/misc/disable_useless_consoles.patch

# don't set a hostname to trigger getting it dynamically on boot
rm /etc/hostname

